/**
 * PublicReportPage.tsx
 *
 * Public, embeddable report card — no auth required.
 * Accessed via /report/:token (generated by Report Studio share).
 * Renders the card full-screen, with a subtle iqpipe attribution footer.
 */

import { useState, useEffect } from "react";
import { useParams, Link } from "react-router-dom";
import { ExternalLink, RefreshCw } from "lucide-react";
import { API_BASE_URL } from "../../config";

// ── Re-use card components from ReportStudioPage ──────────────────────────────
// We inline a lightweight version here to avoid a circular dependency and
// to keep the public page self-contained.

type ReportType = "snapshot" | "funnel" | "digest" | "revenue";
type CardFormat = "linkedin" | "square" | "story";

interface DayCount  { date: string; count: number }
interface FunnelStep { label: string; count: number }

interface ReportData {
  period:    string;
  workspace: { name: string };
  workflows: { total: number; n8n: number; make: number; list: any[] };
  events:    { total: number; successful: number; failed: number; successRate: number; byDay: DayCount[] };
  correlations: { total: number; verified: number; mismatched: number; verifiedRate: number };
  topApps:   { appKey: string; count: number }[];
  kpis:      { contactsEngaged: number; dealsTracked: number; meetingsBooked: number; emailsSent: number; repliesReceived: number };
  funnelSteps: FunnelStep[];
  avgHealthScore: number;
}

interface PublicReportPayload {
  reportType: ReportType;
  cardFormat: CardFormat;
  period:     string;
  insight:    string | null;
  data:       ReportData;
  createdAt:  string;
}

const PERIOD_LABELS: Record<string, string> = {
  "7d": "Last 7 days", "30d": "Last 30 days", "90d": "Last 90 days", "all": "All time",
};

const APP_DOMAINS: Record<string, string> = {
  hubspot: "hubspot.com", salesforce: "salesforce.com", pipedrive: "pipedrive.com",
  attio: "attio.com", instantly: "instantly.ai", lemlist: "lemlist.com",
  smartlead: "smartlead.ai", heyreach: "heyreach.io", apollo: "apollo.io",
  clay: "clay.com", stripe: "stripe.com", calendly: "calendly.com", slack: "slack.com",
};

const FORMAT_ASPECT: Record<CardFormat, string> = {
  linkedin: "aspect-[1.91/1]",
  square:   "aspect-square",
  story:    "aspect-[9/16]",
};

// ── Micro chart components ────────────────────────────────────────────────────

function MiniBarChart({ data, color = "#6366f1", height = 48 }: { data: DayCount[]; color?: string; height?: number }) {
  if (!data.length) return null;
  const max = Math.max(...data.map(d => d.count), 1);
  const w   = 100 / data.length;
  return (
    <svg viewBox={`0 0 100 ${height}`} preserveAspectRatio="none" className="w-full" style={{ height }}>
      {data.map((d, i) => {
        const barH = (d.count / max) * (height - 4);
        return (
          <rect key={d.date}
            x={i * w + w * 0.1} y={height - barH}
            width={w * 0.8} height={barH} rx="1.5"
            fill={color} opacity={0.7 + (d.count / max) * 0.3}
          />
        );
      })}
    </svg>
  );
}

function FunnelSVG({ steps }: { steps: FunnelStep[] }) {
  const valid = steps.filter(s => s.count > 0);
  if (!valid.length) return <div className="text-center text-xs text-slate-600 py-4">No funnel data</div>;
  const max    = valid[0].count;
  const COLORS = ["#6366f1", "#818cf8", "#a5b4fc", "#c7d2fe", "#e0e7ff"];
  return (
    <div className="flex flex-col gap-1 w-full">
      {valid.map((s, i) => (
        <div key={s.label} className="flex items-center gap-2">
          <div className="w-20 text-right text-[10px] text-slate-400 shrink-0">{s.label}</div>
          <div className="flex-1 bg-slate-800 rounded-full h-4 overflow-hidden">
            <div className="h-full rounded-full" style={{ width: `${(s.count / max) * 100}%`, background: COLORS[i] }} />
          </div>
          <div className="w-12 text-[10px] text-slate-300 font-mono">{s.count.toLocaleString()}</div>
        </div>
      ))}
    </div>
  );
}

function DonutSVG({ value, max, color }: { value: number; max: number; color: string }) {
  const r    = 28;
  const circ = 2 * Math.PI * r;
  const dash = max > 0 ? circ * (value / max) : 0;
  return (
    <svg width={72} height={72} viewBox="0 0 72 72">
      <circle cx={36} cy={36} r={r} fill="none" stroke="#1e293b" strokeWidth={8} />
      <circle cx={36} cy={36} r={r} fill="none" stroke={color} strokeWidth={8}
        strokeDasharray={`${dash} ${circ}`} strokeLinecap="round" transform="rotate(-90 36 36)" />
      <text x={36} y={40} textAnchor="middle" fontSize={13} fontWeight="bold" fill="white">
        {max > 0 ? `${Math.round((value / max) * 100)}%` : "—"}
      </text>
    </svg>
  );
}

function AppFavicon({ appKey, size = 18 }: { appKey: string; size?: number }) {
  const domain = APP_DOMAINS[appKey];
  if (!domain) return null;
  return (
    <div className="rounded bg-white/10 overflow-hidden flex items-center justify-center" style={{ width: size, height: size }}>
      <img src={`${API_BASE_URL}/api/proxy/favicon?domain=${domain}`} alt={appKey}
        style={{ width: size - 2, height: size - 2, objectFit: "contain" }}
        onError={e => { (e.target as HTMLImageElement).style.display = "none"; }} />
    </div>
  );
}

function IqpipeLogo({ size = 20 }: { size?: number }) {
  return (
    <div className="flex items-center gap-1.5">
      <div className="rounded-md bg-gradient-to-br from-indigo-500/30 to-purple-500/30 ring-1 ring-indigo-500/50 flex items-center justify-center text-indigo-400 font-bold"
        style={{ width: size, height: size, fontSize: size * 0.5 }}>iq</div>
      <span className="font-bold text-white" style={{ fontSize: size * 0.65 }}>iqpipe</span>
    </div>
  );
}

// ── Card templates (mirrors ReportStudioPage) ─────────────────────────────────

function SnapshotCard({ d, insight }: { d: ReportData; insight: string }) {
  return (
    <div className="relative w-full h-full bg-gradient-to-br from-slate-950 via-slate-900 to-indigo-950/60 p-6 flex flex-col gap-4 overflow-hidden">
      <div className="absolute top-0 right-0 w-64 h-64 bg-indigo-500/5 rounded-full blur-3xl pointer-events-none" />
      <div className="absolute bottom-0 left-0 w-48 h-48 bg-purple-500/5 rounded-full blur-3xl pointer-events-none" />
      <div className="relative flex items-start justify-between">
        <div>
          <div className="text-[10px] font-bold text-indigo-400 tracking-widest uppercase mb-1">GTM Performance Report</div>
          <div className="text-xl font-black text-white">{d.workspace.name}</div>
          <div className="text-xs text-slate-500">{PERIOD_LABELS[d.period] ?? d.period}</div>
        </div>
        <IqpipeLogo size={22} />
      </div>
      <div className="relative grid grid-cols-4 gap-3">
        {[
          { label: "Workflows",     value: d.workflows.total          },
          { label: "Events",        value: d.events.total             },
          { label: "Success Rate",  value: `${d.events.successRate}%` },
          { label: "Verified",      value: d.correlations.verified    },
        ].map(k => (
          <div key={k.label} className="bg-slate-800/50 rounded-xl p-3 border border-slate-700/50">
            <div className="text-2xl font-black text-white tabular-nums">{typeof k.value === "number" ? k.value.toLocaleString() : k.value}</div>
            <div className="text-[10px] text-slate-500">{k.label}</div>
          </div>
        ))}
      </div>
      <div className="relative bg-slate-800/30 rounded-xl p-3 border border-slate-700/30">
        <div className="text-[10px] text-slate-500 mb-2">Events · last 14 days</div>
        <MiniBarChart data={d.events.byDay} color="#6366f1" height={44} />
      </div>
      {d.topApps.length > 0 && (
        <div className="relative flex flex-wrap gap-2">
          {d.topApps.slice(0, 8).map(a => (
            <div key={a.appKey} className="flex items-center gap-1.5 bg-slate-800/60 rounded-lg px-2 py-1 border border-slate-700/40">
              <AppFavicon appKey={a.appKey} size={14} />
              <span className="text-[10px] text-slate-300 capitalize">{a.appKey}</span>
            </div>
          ))}
        </div>
      )}
      {insight && (
        <div className="relative bg-indigo-500/10 border border-indigo-500/20 rounded-xl p-3 text-xs text-slate-300 leading-relaxed italic">{insight}</div>
      )}
      <div className="relative mt-auto flex items-center justify-between">
        <div className="flex gap-3 text-[10px] text-slate-500">
          <span>{d.kpis.contactsEngaged.toLocaleString()} contacts</span>
          {d.kpis.meetingsBooked > 0 && <span>{d.kpis.meetingsBooked} meetings</span>}
        </div>
        <div className="text-[9px] text-slate-600">Verified by iqpipe.com</div>
      </div>
    </div>
  );
}

function FunnelCard({ d, insight }: { d: ReportData; insight: string }) {
  const top = d.funnelSteps[0]?.count ?? 0;
  const bot = d.funnelSteps[d.funnelSteps.length - 1]?.count ?? 0;
  const conv = top > 0 ? ((bot / top) * 100).toFixed(2) : "0";
  return (
    <div className="relative w-full h-full bg-gradient-to-br from-slate-950 via-slate-900 to-violet-950/50 p-6 flex flex-col gap-4 overflow-hidden">
      <div className="absolute top-0 right-0 w-56 h-56 bg-violet-500/5 rounded-full blur-3xl pointer-events-none" />
      <div className="relative flex items-start justify-between">
        <div>
          <div className="text-[10px] font-bold text-violet-400 tracking-widest uppercase mb-1">Outbound Campaign Funnel</div>
          <div className="text-xl font-black text-white">{d.workspace.name}</div>
          <div className="text-xs text-slate-500">{PERIOD_LABELS[d.period] ?? d.period}</div>
        </div>
        <IqpipeLogo size={22} />
      </div>
      <div className="relative grid grid-cols-3 gap-3">
        <div className="bg-slate-800/50 rounded-xl p-3 border border-slate-700/50">
          <div className="text-2xl font-black text-white">{top.toLocaleString()}</div>
          <div className="text-[10px] text-slate-500">Total sourced</div>
        </div>
        <div className="bg-slate-800/50 rounded-xl p-3 border border-slate-700/50">
          <div className="text-2xl font-black text-emerald-400">{d.funnelSteps.find(s => s.label === "Booked")?.count ?? 0}</div>
          <div className="text-[10px] text-slate-500">Meetings booked</div>
        </div>
        <div className="bg-slate-800/50 rounded-xl p-3 border border-slate-700/50">
          <div className="text-2xl font-black text-violet-400">{conv}%</div>
          <div className="text-[10px] text-slate-500">Source → booked</div>
        </div>
      </div>
      <div className="relative flex-1 flex items-center">
        <FunnelSVG steps={d.funnelSteps} />
      </div>
      {insight && (
        <div className="relative bg-violet-500/10 border border-violet-500/20 rounded-xl p-3 text-xs text-slate-300 italic">{insight}</div>
      )}
      <div className="relative flex items-center justify-between">
        <span className="text-[10px] text-slate-500">{d.kpis.emailsSent.toLocaleString()} emails · {d.kpis.repliesReceived} replies</span>
        <div className="text-[9px] text-slate-600">Verified by iqpipe.com</div>
      </div>
    </div>
  );
}

function DigestCard({ d, insight }: { d: ReportData; insight: string }) {
  const last7  = d.events.byDay.slice(-7);
  const prev7  = d.events.byDay.slice(-14, -7);
  const tot7   = last7.reduce((a, x) => a + x.count, 0);
  const totP   = prev7.reduce((a, x) => a + x.count, 0);
  const delta  = totP > 0 ? Math.round(((tot7 - totP) / totP) * 100) : 0;
  const best   = [...last7].sort((a, b) => b.count - a.count)[0];
  return (
    <div className="relative w-full h-full bg-gradient-to-br from-slate-950 via-slate-900 to-sky-950/40 p-6 flex flex-col gap-4 overflow-hidden">
      <div className="absolute top-0 left-0 w-64 h-64 bg-sky-500/5 rounded-full blur-3xl pointer-events-none" />
      <div className="relative flex items-start justify-between">
        <div>
          <div className="text-[10px] font-bold text-sky-400 tracking-widest uppercase mb-1">Weekly GTM Digest</div>
          <div className="text-xl font-black text-white">{d.workspace.name}</div>
          <div className="text-xs text-slate-500">{PERIOD_LABELS[d.period] ?? d.period}</div>
        </div>
        <IqpipeLogo size={22} />
      </div>
      <div className="relative grid grid-cols-3 gap-3">
        <div className="bg-slate-800/50 rounded-xl p-3 border border-slate-700/50">
          <div className="text-2xl font-black text-white">{tot7.toLocaleString()}</div>
          <div className="text-[10px] text-slate-500">Events this week</div>
        </div>
        <div className="bg-slate-800/50 rounded-xl p-3 border border-slate-700/50">
          <div className={`text-2xl font-black ${delta >= 0 ? "text-emerald-400" : "text-red-400"}`}>{delta >= 0 ? "+" : ""}{delta}%</div>
          <div className="text-[10px] text-slate-500">vs prev week</div>
        </div>
        <div className="bg-slate-800/50 rounded-xl p-3 border border-slate-700/50">
          <div className="text-2xl font-black text-sky-400">{d.avgHealthScore}%</div>
          <div className="text-[10px] text-slate-500">Avg health</div>
        </div>
      </div>
      <div className="relative bg-slate-800/30 rounded-xl p-3 border border-slate-700/30 flex-1">
        <div className="text-[10px] text-slate-500 mb-2">Events · last 7 days</div>
        <MiniBarChart data={last7} color="#38bdf8" height={56} />
        {best && (
          <div className="mt-2 text-[10px] text-slate-500">
            Best: <span className="text-sky-400 font-semibold">
              {new Date(best.date).toLocaleDateString("en-US", { weekday: "short", month: "short", day: "numeric" })}
            </span> — {best.count} events
          </div>
        )}
      </div>
      {insight && (
        <div className="relative bg-sky-500/10 border border-sky-500/20 rounded-xl p-3 text-xs text-slate-300 italic">{insight}</div>
      )}
      <div className="relative flex items-center justify-between">
        <span className="text-[10px] text-slate-500">{d.workflows.total} workflows · {d.kpis.contactsEngaged} contacts</span>
        <div className="text-[9px] text-slate-600">Verified by iqpipe.com</div>
      </div>
    </div>
  );
}

function RevenueCard({ d, insight }: { d: ReportData; insight: string }) {
  return (
    <div className="relative w-full h-full bg-gradient-to-br from-slate-950 via-slate-900 to-emerald-950/40 p-6 flex flex-col gap-4 overflow-hidden">
      <div className="absolute bottom-0 right-0 w-64 h-64 bg-emerald-500/5 rounded-full blur-3xl pointer-events-none" />
      <div className="relative flex items-start justify-between">
        <div>
          <div className="text-[10px] font-bold text-emerald-400 tracking-widest uppercase mb-1">Revenue Signal</div>
          <div className="text-xl font-black text-white">{d.workspace.name}</div>
          <div className="text-xs text-slate-500">{PERIOD_LABELS[d.period] ?? d.period}</div>
        </div>
        <IqpipeLogo size={22} />
      </div>
      <div className="relative grid grid-cols-4 gap-3">
        {[
          { label: "Verified",   value: d.correlations.verified,           color: "text-emerald-400" },
          { label: "Deals",      value: d.kpis.dealsTracked,               color: "text-white"       },
          { label: "Meetings",   value: d.kpis.meetingsBooked,             color: "text-sky-400"     },
          { label: "Verify rate",value: `${d.correlations.verifiedRate}%`, color: "text-violet-400"  },
        ].map(k => (
          <div key={k.label} className="bg-slate-800/50 rounded-xl p-3 border border-slate-700/50">
            <div className={`text-2xl font-black ${k.color}`}>{typeof k.value === "number" ? k.value.toLocaleString() : k.value}</div>
            <div className="text-[10px] text-slate-500">{k.label}</div>
          </div>
        ))}
      </div>
      <div className="relative grid grid-cols-2 gap-3 flex-1">
        <div className="bg-slate-800/30 rounded-xl p-4 border border-slate-700/30 flex items-center gap-4">
          <DonutSVG value={d.correlations.verified} max={d.correlations.total} color="#34d399" />
          <div>
            <div className="text-sm font-bold text-white">Correlation rate</div>
            <div className="text-xs text-slate-500 mt-0.5">{d.correlations.verified} of {d.correlations.total} app events matched</div>
          </div>
        </div>
        <div className="bg-slate-800/30 rounded-xl p-3 border border-slate-700/30">
          <div className="text-[10px] text-slate-500 mb-2">Top sources</div>
          <div className="space-y-1.5">
            {d.topApps.slice(0, 4).map(a => (
              <div key={a.appKey} className="flex items-center gap-2">
                <AppFavicon appKey={a.appKey} size={14} />
                <div className="flex-1 bg-slate-700/50 rounded-full h-2 overflow-hidden">
                  <div className="h-full bg-emerald-500/70 rounded-full" style={{ width: `${Math.round(a.count / (d.topApps[0]?.count || 1) * 100)}%` }} />
                </div>
                <span className="text-[10px] text-slate-400 w-8 text-right">{a.count}</span>
              </div>
            ))}
          </div>
        </div>
      </div>
      {insight && (
        <div className="relative bg-emerald-500/10 border border-emerald-500/20 rounded-xl p-3 text-xs text-slate-300 italic">{insight}</div>
      )}
      <div className="relative flex items-center justify-between">
        <span className="text-[10px] text-slate-500">{d.kpis.contactsEngaged} contacts · {d.events.total} events</span>
        <div className="text-[9px] text-slate-600">Verified by iqpipe.com</div>
      </div>
    </div>
  );
}

// ── Public page ───────────────────────────────────────────────────────────────

export default function PublicReportPage() {
  const { token }  = useParams<{ token: string }>();
  const [report, setReport]    = useState<PublicReportPayload | null>(null);
  const [loading, setLoading]  = useState(true);
  const [notFound, setNotFound] = useState(false);

  useEffect(() => {
    if (!token) return;
    fetch(`${API_BASE_URL}/api/report-studio/public/${token}`)
      .then(r => {
        if (!r.ok) { setNotFound(true); return null; }
        return r.json();
      })
      .then(d => { if (d) setReport(d); })
      .catch(() => setNotFound(true))
      .finally(() => setLoading(false));
  }, [token]);

  const aspectClass = report ? FORMAT_ASPECT[report.cardFormat] ?? FORMAT_ASPECT.linkedin : FORMAT_ASPECT.linkedin;

  if (loading) {
    return (
      <div className="min-h-screen bg-slate-950 flex items-center justify-center">
        <RefreshCw size={24} className="text-indigo-400 animate-spin" />
      </div>
    );
  }

  if (notFound || !report) {
    return (
      <div className="min-h-screen bg-slate-950 flex flex-col items-center justify-center gap-4 text-center px-6">
        <div className="text-4xl font-black text-slate-700">404</div>
        <p className="text-slate-500 text-sm">This report link has expired or doesn't exist.</p>
        <Link to="/" className="text-indigo-400 hover:text-indigo-300 text-sm flex items-center gap-1.5">
          <ExternalLink size={14} /> Go to iqpipe
        </Link>
      </div>
    );
  }

  const { data, insight, reportType } = report;
  const cardProps = { d: data, insight: insight ?? "" };

  return (
    <div className="min-h-screen bg-slate-950 flex flex-col items-center justify-center px-4 py-8 gap-6">

      {/* Card */}
      <div className={`w-full max-w-2xl ${aspectClass} rounded-2xl overflow-hidden border border-slate-700/50 shadow-2xl shadow-indigo-500/10`}>
        {reportType === "snapshot" && <SnapshotCard {...cardProps} />}
        {reportType === "funnel"   && <FunnelCard   {...cardProps} />}
        {reportType === "digest"   && <DigestCard   {...cardProps} />}
        {reportType === "revenue"  && <RevenueCard  {...cardProps} />}
      </div>

      {/* Footer attribution */}
      <div className="flex items-center gap-3 text-xs text-slate-600">
        <span>Generated with</span>
        <Link
          to="/"
          className="flex items-center gap-1.5 text-indigo-400 hover:text-indigo-300 font-semibold transition-colors"
        >
          <div className="h-4 w-4 rounded bg-gradient-to-br from-indigo-500/30 to-purple-500/30 ring-1 ring-indigo-500/50 flex items-center justify-center text-[8px] font-bold">iq</div>
          iqpipe
        </Link>
        <span>·</span>
        <span>GTM Observability Platform</span>
        <span>·</span>
        <span>{new Date(report.createdAt).toLocaleDateString()}</span>
      </div>
    </div>
  );
}
